baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Hugo Learn Documentation"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false

[params]
  description = "Documentation for Hugo Learn Theme"
  author = "Johnny"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "blue"
  disableLanguageSwitchingButton = "true"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> cnki"
identifier = "ds"
url = "http://www.cnki.net"
weight = 10


[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 西工网协"
url = "http://xgwx.us"
weight = 31

